#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Sirac Ozmen
#
# Compiles Android's generic key layout (tools/androidkeys/) into the
# table of src/android_keys.h: for each Android key code, the Linux input
# code a generic keyboard sends for it, which src/evdev.c turns into the
# API's key code. A key code the layout gives several input codes takes
# the lowest; entries with flags (FUNCTION, the Fn layer) are left out.
#
# usage: gen_android_keys.py <output.c>

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "tools", "androidkeys")
KEYCODE = re.compile(r"^\s*AKEYCODE_([A-Z0-9_]+)\s*=\s*(\d+),")
LAYOUT = re.compile(r"^key\s+(\d+)\s+([A-Z0-9_]+)\s*(.*)$")


def main():
    numbers = {}
    with open(os.path.join(DATA, "keycodes.h"), encoding="utf-8") as header:
        for line in header:
            match = KEYCODE.match(line)
            if match:
                numbers[match.group(1)] = int(match.group(2))
    evdev = {}
    with open(os.path.join(DATA, "Generic.kl"), encoding="utf-8") as layout:
        for line in layout:
            match = LAYOUT.match(line.split("#", 1)[0].strip())
            if not match or match.group(3).strip() or match.group(2) not in numbers:
                continue
            code = numbers[match.group(2)]
            scan = int(match.group(1))
            if code not in evdev or scan < evdev[code]:
                evdev[code] = scan
    size = max(evdev) + 1
    rows = []
    values = [evdev.get(code, 0) for code in range(size)]
    for start in range(0, size, 12):
        rows.append("    " + ", ".join(f"{value:3d}" for value in values[start:start + 12]) + ",")
    with open(sys.argv[1], "w", encoding="utf-8") as out:
        out.write(f"""// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Sirac Ozmen
//
// The Linux input code of each Android key code. Generated by
// tools/gen_android_keys.py from tools/androidkeys/Generic.kl and
// keycodes.h (the Android Open Source Project); do not edit.
// {len(evdev)} key codes.
// clang-format off

#include "../android_keys.h"

static const uint16_t s_evdev[{size}] = {{
""")
        out.write("\n".join(rows) + "\n};\n// clang-format on\n\n")
        out.write("""uint32_t mwinAndroidEvdevOf(int32_t keyCode)
{
    size_t count = sizeof(s_evdev) / sizeof(s_evdev[0]);
    return keyCode >= 0 && (size_t)keyCode < count ? s_evdev[keyCode] : 0;
}
""")
    print(f"wrote {sys.argv[1]} ({len(evdev)} key codes)")


if __name__ == "__main__":
    main()
