#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Sirac Ozmen
#
# Compiles SDL_GameControllerDB (tools/gamepaddb/) into the mapping tables
# of src/pad_db.h: for one platform, each device's entry and the distinct
# mappings they share. Entries for SDL's own drivers (a driver byte in the
# GUID) are left out: the backends read devices as the platform gives
# them. As SDL does, a later entry for a device replaces an earlier one.
#
# usage: gen_gamepad_db.py <platform> <output.c>   (platform: Linux or Windows)

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "tools", "gamepaddb", "gamecontrollerdb.txt")

# The database's names of the controls, in mwinGamepadButton then
# mwinGamepadAxis order.
CONTROLS = ["dpup", "dpdown", "dpleft", "dpright", "a", "b", "x", "y", "leftshoulder",
            "rightshoulder", "leftstick", "rightstick", "start", "back", "guide",
            "leftx", "lefty", "rightx", "righty", "lefttrigger", "righttrigger"]
STICKS = ["leftx", "lefty", "rightx", "righty"]
SOURCE = re.compile(r"^([+-]?)([abh])(\d+)(?:\.(\d+))?(~?)$")


def source(text):
    """Encodes a source as mwinPadSource, or None when it cannot be."""
    match = SOURCE.match(text)
    if not match:
        return None
    half, kind, number, mask, inverted = match.groups()
    number = int(number)
    if kind == "b" and number < 256 and not half and not inverted:
        return 1 << 14 | number
    if kind == "a" and number < 256:
        halves = {"": 0, "+": 1, "-": 2}[half]
        return 2 << 14 | (0x400 if inverted else 0) | halves << 8 | number
    if kind == "h" and number < 4 and mask and int(mask) in (1, 2, 4, 8):
        return 3 << 14 | number << 4 | int(mask)
    return None


def parse(platform):
    """Yields (key, sources, halves) for the platform's entries."""
    for line in open(DATA, encoding="utf-8"):
        fields = line.strip().rstrip(",").split(",")
        if (len(fields) < 3 or ("platform:" + platform) not in fields or
                not re.fullmatch(r"[0-9a-fA-F]{32}", fields[0])):
            continue
        guid = bytes.fromhex(fields[0])
        if len(guid) != 16 or guid[14] != 0 or any(guid[i] for i in (6, 7, 10, 11)):
            continue
        key = tuple(guid[i] | guid[i + 1] << 8 for i in (0, 4, 8, 12))
        sources = [0] * len(CONTROLS)
        halves = [0] * 2 * len(STICKS)
        for field in fields[2:]:
            name, _, value = field.partition(":")
            encoded = source(value)
            if encoded is None:
                continue
            if name in CONTROLS:
                sources[CONTROLS.index(name)] = encoded
            elif name[:1] in "+-" and name[1:] in STICKS:
                halves[2 * STICKS.index(name[1:]) + (name[0] == "+")] = encoded
        yield key, tuple(sources), tuple(halves)


def main():
    platform, output = sys.argv[1], sys.argv[2]
    devices = {}
    for key, sources, halves in parse(platform):
        devices[key] = (sources, halves)
    mappings = []
    halves_rows = []
    entries = []
    for key in sorted(devices):
        sources, halves = devices[key]
        row = 0
        if any(halves):
            if halves not in halves_rows:
                halves_rows.append(halves)
            row = halves_rows.index(halves) + 1
        mapping = (sources, row)
        if mapping not in mappings:
            mappings.append(mapping)
        entries.append((key, mappings.index(mapping)))
    size = len(entries) * 10 + len(mappings) * 44 + len(halves_rows) * 16
    out = [
        "// SPDX-License-Identifier: MIT",
        "// Copyright (c) 2026 Sirac Ozmen",
        "//",
        f"// The {platform} gamepad mappings. Generated by tools/gen_gamepad_db.py from",
        "// tools/gamepaddb/gamecontrollerdb.txt (SDL_GameControllerDB); do not edit.",
        f"// {len(entries)} devices, {len(mappings)} mappings, {size} bytes of tables.",
        "// clang-format off",
        "",
        '#include "../pad_db.h"',
        "",
        "static const mwinPadMapping s_mappings[] = {",
    ]
    for sources, row in mappings:
        out.append("    {{" + ", ".join(f"0x{s:04X}" for s in sources) + f"}}, {row}}},")
    out.append("};")
    out.append("")
    out.append(f"static const mwinPadSource s_halves[][MWIN_PAD_HALVES] = {{")
    for halves in halves_rows or [(0,) * 8]:
        out.append("    {" + ", ".join(f"0x{s:04X}" for s in halves) + "},")
    out.append("};")
    out.append("")
    out.append("static const mwinPadEntry s_entries[] = {")
    for (bus, vendor, product, version), mapping in entries:
        out.append(f"    {{0x{bus:04X}, 0x{vendor:04X}, 0x{product:04X}, 0x{version:04X}, {mapping}}},")
    out.append("};")
    out.append("")
    out.append(f"const mwinPadDatabase mwin{platform}PadDatabase = {{")
    out.append("    s_entries, sizeof(s_entries) / sizeof(s_entries[0]), s_mappings, s_halves,")
    out.append("};")
    with open(output, "w", encoding="utf-8", newline="\n") as file:
        file.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
