# The Wayland backend (W7 in the design notes). The protocol code is
# generated from the protocol XML into the build tree with
# wayland-scanner: a client header and the interface definitions of each
# protocol, the core wayland.xml included. Every interface is renamed
# with an mwin_ prefix (wayland-names.h, forced into the generated code
# and included first by the backend), so the definitions never collide
# with another library's copy in a static link. libwayland-client itself
# is opened at run time; nothing of it is linked.

find_package(PkgConfig REQUIRED)
pkg_check_modules(MWIN_WAYLAND QUIET wayland-client>=1.22 wayland-scanner wayland-protocols>=1.32)
if(NOT MWIN_WAYLAND_FOUND)
    message(FATAL_ERROR "The Wayland backend needs the development files of wayland-client "
        "(1.22 or later), wayland-scanner and wayland-protocols (1.32 or later): install "
        "them (libwayland-dev and wayland-protocols on Debian and Ubuntu) or configure "
        "with -DMAUL_WINDOW_WAYLAND=OFF.")
endif()
pkg_get_variable(MWIN_WAYLAND_SCANNER wayland-scanner wayland_scanner)
pkg_get_variable(MWIN_PROTOCOLS_DIR wayland-protocols pkgdatadir)
pkg_get_variable(MWIN_WAYLAND_DATA_DIR wayland-client pkgdatadir)
pkg_get_variable(MWIN_WAYLAND_INCLUDE_DIR wayland-client includedir)

set(MWIN_PROTOCOL_OUT ${PROJECT_BINARY_DIR}/wayland)
file(MAKE_DIRECTORY ${MWIN_PROTOCOL_OUT})
set(MWIN_WAYLAND_NAMES "")

# mwin_wayland_protocol(name xml [CODE_ONLY]): name-protocol.c, and
# name-protocol.h unless CODE_ONLY.
function(mwin_wayland_protocol name xml)
    set(code ${MWIN_PROTOCOL_OUT}/${name}-protocol.c)
    add_custom_command(OUTPUT ${code}
        COMMAND ${MWIN_WAYLAND_SCANNER} private-code ${xml} ${code}
        DEPENDS ${xml} VERBATIM)
    set(outputs ${code})
    if(NOT "CODE_ONLY" IN_LIST ARGN)
        set(header ${MWIN_PROTOCOL_OUT}/${name}-protocol.h)
        add_custom_command(OUTPUT ${header}
            COMMAND ${MWIN_WAYLAND_SCANNER} client-header ${xml} ${header}
            DEPENDS ${xml} VERBATIM)
        list(APPEND outputs ${header})
    endif()
    target_sources(maul-window PRIVATE ${outputs})
    # The scanner's code keeps its own style.
    set_source_files_properties(${code} PROPERTIES
        COMPILE_OPTIONS "-w;-include;${MWIN_PROTOCOL_OUT}/wayland-names.h"
        OBJECT_DEPENDS ${MWIN_PROTOCOL_OUT}/wayland-names.h)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${xml})
    file(READ ${xml} text)
    string(REGEX MATCHALL "<interface name=\"[a-z0-9_]+\"" found "${text}")
    foreach(match IN LISTS found)
        string(REGEX REPLACE "<interface name=\"([a-z0-9_]+)\"" "\\1" interface "${match}")
        string(APPEND MWIN_WAYLAND_NAMES
            "#define ${interface}_interface mwin_${interface}_interface\n")
    endforeach()
    set(MWIN_WAYLAND_NAMES "${MWIN_WAYLAND_NAMES}" PARENT_SCOPE)
endfunction()

mwin_wayland_protocol(wayland ${MWIN_WAYLAND_DATA_DIR}/wayland.xml CODE_ONLY)
mwin_wayland_protocol(xdg-shell ${MWIN_PROTOCOLS_DIR}/stable/xdg-shell/xdg-shell.xml)
mwin_wayland_protocol(viewporter ${MWIN_PROTOCOLS_DIR}/stable/viewporter/viewporter.xml)
mwin_wayland_protocol(fractional-scale-v1
    ${MWIN_PROTOCOLS_DIR}/staging/fractional-scale/fractional-scale-v1.xml)
mwin_wayland_protocol(xdg-decoration-unstable-v1
    ${MWIN_PROTOCOLS_DIR}/unstable/xdg-decoration/xdg-decoration-unstable-v1.xml)

file(CONFIGURE OUTPUT ${MWIN_PROTOCOL_OUT}/wayland-names.h CONTENT
"// Generated by cmake/Wayland.cmake: the library's names for the Wayland
// protocol interfaces it defines.
#ifndef MAUL_WINDOW_WAYLAND_NAMES_H
#define MAUL_WINDOW_WAYLAND_NAMES_H
${MWIN_WAYLAND_NAMES}#endif
")

# The generated headers and libwayland's own are outside the rules.
target_include_directories(maul-window SYSTEM PRIVATE ${MWIN_PROTOCOL_OUT}
    ${MWIN_WAYLAND_INCLUDE_DIR})
target_sources(maul-window PRIVATE
    src/backend_wayland.c
    src/wayland_api.c
    src/wayland_output.c
    src/wayland_window.c)
target_compile_definitions(maul-window PRIVATE MAUL_WINDOW_WAYLAND)
# poll, clock_gettime and dlopen are POSIX, outside strict C.
set_source_files_properties(src/backend_wayland.c src/wayland_api.c src/wayland_output.c
    src/wayland_window.c PROPERTIES COMPILE_DEFINITIONS _POSIX_C_SOURCE=200809L)
target_link_libraries(maul-window PRIVATE ${CMAKE_DL_LIBS})
if(CMAKE_DL_LIBS)
    string(APPEND MAUL_PKG_LIBS_PRIVATE " -l${CMAKE_DL_LIBS}")
endif()
# The library must reach libwayland only through the loaded table: a
# call to one of its functions by name fails the shared link.
if(MAUL_WINDOW_BUILD_SHARED AND NOT MAUL_WINDOW_SANITIZE AND NOT MAUL_WINDOW_TSAN)
    target_link_options(maul-window PRIVATE "LINKER:--no-undefined")
endif()
